DROP TABLE IF EXISTS vehicles;
DROP TABLE IF EXISTS renter_profiles;
DROP TABLE IF EXISTS owner_profiles;
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS registered_users;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS roles;


--roles
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(255) UNIQUE NOT NULL
);

--locations
CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(255) NOT NULL,
    district VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);

--registered_users
CREATE TABLE registered_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    date_of_birth DATE,
    phone_number VARCHAR(255),
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

--user_role
CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES registered_users(id),
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

--owner_profiles
CREATE TABLE owner_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registered_user_id BIGINT UNIQUE NOT NULL,
    image_url VARCHAR(255),
    public_image_id VARCHAR(255),
    FOREIGN KEY (registered_user_id) REFERENCES registered_users(id) ON DELETE CASCADE
);

--renter_profiles
CREATE TABLE renter_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registered_user_id BIGINT UNIQUE NOT NULL,
    type_license VARCHAR(255) NOT NULL,
    license_number VARCHAR(255) NOT NULL,
    expired_date DATE,
    image_url VARCHAR(255),
    public_image_id VARCHAR(255),
    FOREIGN KEY (registered_user_id) REFERENCES registered_users(id) ON DELETE CASCADE
);

--vehicles
CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vin VARCHAR(255) UNIQUE NOT NULL,
    plate_number VARCHAR(255) UNIQUE NOT NULL,
    insurance_number VARCHAR(255),
    model VARCHAR(255),
    brand VARCHAR(255),
    "year" INT,
    color VARCHAR(255),
    seater VARCHAR(255),
    child_seats_number INT,
    fuel_type_car VARCHAR(255),
    fuel_consumption VARCHAR(255),
    image_url VARCHAR(255),
    public_image_id VARCHAR(255),
    owner_id BIGINT NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES owner_profiles(id) ON DELETE CASCADE
);


-- INSERT DATA

-- roles
INSERT INTO roles (id, role) VALUES (1, 'ROLE_ADMIN');
INSERT INTO roles (id, role) VALUES (2, 'ROLE_RENTER');
INSERT INTO roles (id, role) VALUES (3, 'ROLE_OWNER');

-- registered_users (passwords are BCrypt hashed for "password123")
INSERT INTO registered_users (id, first_name, last_name, date_of_birth, phone_number, username, email, password)
VALUES (1, 'Admin', 'User', '1990-01-01', '+34600000001', 'admin1', 'admin@test.com', '$2a$10$N9qo8uLOickgx2ZMRZoMye/R3BrNnUQxcz8xHdYmJQqLjRqKzRnEy');

INSERT INTO registered_users (id, first_name, last_name, date_of_birth, phone_number, username, email, password)
VALUES (2, 'Renter', 'One', '1995-05-15', '+34600000002', 'renter1', 'renter1@test.com', '$2a$10$N9qo8uLOickgx2ZMRZoMye/R3BrNnUQxcz8xHdYmJQqLjRqKzRnEy');

INSERT INTO registered_users (id, first_name, last_name, date_of_birth, phone_number, username, email, password)
VALUES (3, 'Owner', 'One', '1992-03-20', '+34600000003', 'owner1', 'owner1@test.com', '$2a$10$N9qo8uLOickgx2ZMRZoMye/R3BrNnUQxcz8xHdYmJQqLjRqKzRnEy');

INSERT INTO registered_users (id, first_name, last_name, date_of_birth, phone_number, username, email, password)
VALUES (4, 'Renter', 'Two', '1993-07-10', '+34600000004', 'renter2', 'renter2@test.com', '$2a$10$N9qo8uLOickgx2ZMRZoMye/R3BrNnUQxcz8xHdYmJQqLjRqKzRnEy');

-- user_role assignments
INSERT INTO user_role (user_id, role_id) VALUES (1, 1); -- admin1 -> ADMIN
INSERT INTO user_role (user_id, role_id) VALUES (2, 2); -- renter1 -> RENTER
INSERT INTO user_role (user_id, role_id) VALUES (3, 3); -- owner1 -> OWNER
INSERT INTO user_role (user_id, role_id) VALUES (4, 2); -- renter2 -> RENTER

-- locations
INSERT INTO locations (id, city, district, address) VALUES (1, 'Valencia', 'Ciutat Vella', 'C/Ruzafa, 4, 46004');
INSERT INTO locations (id, city, district, address) VALUES (2, 'Barcelona', 'Eixample', 'C/Balmes, 100, 08008');
INSERT INTO locations (id, city, district, address) VALUES (3, 'Madrid', 'Centro', 'C/Gran Via, 50, 28013');

-- owner_profiles
INSERT INTO owner_profiles (id, registered_user_id, image_url, public_image_id)
VALUES (1, 3, 'http://cloudinary.com/owner1.png', 'owner1_public_id');

-- renter_profiles
INSERT INTO renter_profiles (id, registered_user_id, type_license, license_number, expired_date, image_url, public_image_id)
VALUES (1, 4, 'B', 'LIC123456', '2027-12-31', 'http://cloudinary.com/renter2_license.png', 'renter2_license_id');